#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


# General configs
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Some ENV exports
# Solución para problemas de clic en Chromium-based browsers
export XDG_CURRENT_DESKTOP=bspwm
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_QPA_PLATFORM="xcb"

#Rules for browser and left-click issues
bspc rule -a Brave-browser state=floating focus=on
bspc config focus_follows_pointer false
bspc config click_to_focus true

# Smooth animations
bspc config move_duration       200

# Gruvbox Dark colors
bspc config normal_border_color   "#3c3836"
bspc config focused_border_color  "#fabd2f"
bspc config active_border_color   "#fe8019"
bspc config presel_feedback_color "#83a598"

#GTK CONFIG

# Configuración GTK/QT
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_STYLE_OVERRIDE="kvantum"

#Autostart 
picom --experimental-backends &
~/.config/polybar/launch.sh &
sxhdk &
feh --bg-fill ~/.config/wallpapers/gruvbox.png
xsetroot -cursor_name left_ptr
xset -b
clipmenud &
deadd-notification-center &

# Clipboard monitor
killall -q clipboard_monitor.sh
~/.config/polybar/scripts/clipboard_monitor.sh &

# Notifications: ensure dunst is running
killall -q dunst
dunst &

# Actualizar estado inicial
~/.config/polybar/scripts/notifications.sh update

# Lanzar el applet de NetworkManager en el tray
# nm-applet & disown
